# Generated by Django 4.0 on 2022-02-14 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Группа', max_length=50, verbose_name='Введите название группы')),
                ('year_of_release', models.IntegerField(help_text='Год основания', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2022)], verbose_name='Введите год основания')),
                ('style', models.CharField(help_text='Стиль', max_length=50, null=True, verbose_name='Введите музыкальный стиль')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Альбом', max_length=50, verbose_name='Введите название альбома')),
                ('year_of_release', models.IntegerField(help_text='Год выпуска', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2022)], verbose_name='Введите год выпуска')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='task_22.musicband')),
            ],
        ),
    ]
