# Generated by Django 4.0 on 2022-02-14 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_22', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Трек', max_length=50, verbose_name='Введите название композиции')),
                ('duration', models.IntegerField(help_text='Длительность', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Введите длительность композиции')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='task_22.album')),
            ],
        ),
    ]
