# Generated by Django 4.0 on 2022-02-14 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, help_text='Введите имя', max_length=70, verbose_name='Имя')),
                ('lastname', models.CharField(default=None, help_text='Введите фамилию', max_length=70, verbose_name='Фамилия')),
                ('age', models.IntegerField(default=None, help_text='Введите возраст', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст')),
                ('test', models.CharField(default='Some text', max_length=1000, null=True, verbose_name='Комментарий')),
            ],
        ),
    ]
