# Generated by Django 4.0 on 2022-02-16 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(help_text='Input image link', max_length=500, verbose_name='Link')),
                ('height', models.IntegerField(default=480, help_text='Input picture height', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height')),
                ('weight', models.IntegerField(default=640, help_text='Input picture weight', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight')),
                ('comment', models.CharField(default='Nature image', help_text='Input comment to picture', max_length=200, null=True, verbose_name='Comment')),
            ],
        ),
    ]
