# Generated by Django 4.0 on 2022-02-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Input image url here', max_length=500, verbose_name='Image url')),
                ('type', models.CharField(help_text='Input type of pet here', max_length=3, verbose_name='Pet')),
                ('date_of_creating', models.DateTimeField(auto_now_add=True, help_text='Input date of creating', null=True, verbose_name='Date')),
                ('pic_type', models.CharField(default='', help_text='Input picture format', max_length=20, verbose_name='Format')),
            ],
        ),
    ]
